/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#414755",
        "surface": "#10131b",
        "on-secondary-fixed": "#1f1b19",
        "surface-variant": "#31353d",
        "on-secondary-container": "#bcb3b0",
        "tertiary": "#ffb595",
        "on-tertiary-container": "#4c1a00",
        "on-primary-container": "#00285c",
        "surface-bright": "#363942",
        "surface-container-lowest": "#0b0e16",
        "on-surface": "#F9F9F9",
        "background": "#1A1C1C",
        "surface-tint": "#adc6ff",
        "on-error": "#690005",
        "surface-container": "#1c2028",
        "on-primary": "#002e69",
        "inverse-primary": "#005bc1",
        "tertiary-fixed": "#ffdbcc",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#ef6719",
        "inverse-surface": "#e0e2ed",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004493",
        "on-background": "#e0e2ed",
        "on-tertiary-fixed": "#351000",
        "primary": "#adc6ff",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-high": "#272a32",
        "on-error-container": "#ffdad6",
        "secondary": "#cdc5c1",
        "surface-dim": "#10131b",
        "outline": "#333333",
        "error": "#FF3B30",
        "on-secondary-fixed-variant": "#4b4643",
        "secondary-container": "#4b4643",
        "on-tertiary": "#571e00",
        "primary-container": "#4b8eff",
        "secondary-fixed-dim": "#cdc5c1",
        "surface-container-low": "#181c23",
        "inverse-on-surface": "#2d3039",
        "on-tertiary-fixed-variant": "#7c2e00",
        "tertiary-fixed-dim": "#ffb595",
        "secondary-fixed": "#eae1dd",
        "on-primary-fixed": "#001a41",
        "on-secondary": "#342f2d",
        "on-surface-variant": "#c1c6d7",
        "surface-container-highest": "#31353d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        gutter: "24px",
        unit: "8px",
      },
      fontFamily: {
        "body-lg": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "headline-lg": ["Noto Serif", "serif"],
        "headline-sm": ["Noto Serif", "serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Noto Serif", "serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Noto Serif", "serif"],
        code: ["Manrope", "monospace"],
        "body-md": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "52px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.5px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        code: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
