import React, { useRef } from 'react';
import html2canvas from 'html2canvas';

const TrustCertificate = ({ analysisResult, fileName, hash, dnaColors }) => {
  const certificateRef = useRef(null);

  const isAuthentic = analysisResult?.verdict === 'AUTHENTIC';
  const borderColor = isAuthentic ? 'border-green-500' : 'border-error';
  const badgeColor = isAuthentic ? 'bg-green-500/20 text-green-500' : 'bg-error/20 text-error';
  const badgeIcon = isAuthentic ? 'verified' : 'warning';
  
  // Use first 16 colors for grid, fallback to gray if not enough
  const gridColors = Array.from({ length: 16 }).map((_, i) => 
    dnaColors && dnaColors[i] ? dnaColors[i] : '#333333'
  );

  const handleDownload = async () => {
    if (!certificateRef.current) return;
    try {
      const canvas = await html2canvas(certificateRef.current, {
        backgroundColor: '#10131b',
        scale: 2, // Higher quality
      });
      const url = canvas.toDataURL('image/png');
      const a = document.createElement('a');
      a.href = url;
      a.download = `TrustCertificate-${fileName}.png`;
      a.click();
    } catch (err) {
      console.error("Error generating certificate", err);
    }
  };

  const handleCopyReport = () => {
    const reportText = `DeepGuard+ Forensic Analysis Report
File: ${fileName}
Verdict: ${analysisResult?.verdict || 'UNKNOWN'}
Confidence: ${analysisResult?.confidence || 0}%
Risk Level: ${analysisResult?.riskLevel || 'UNKNOWN'}
SHA-256 Hash: ${hash || 'N/A'}
Timestamp: ${new Date().toISOString()}

This certificate was generated by DeepGuard+ Forensic Systems.
Compliant with DPDP Act 2023 & IT Act 2000.`;
    navigator.clipboard.writeText(reportText)
      .then(() => alert('Report copied to clipboard!'))
      .catch(err => console.error("Could not copy text: ", err));
  };

  return (
    <div className="flex flex-col items-center gap-6 w-full max-w-4xl mx-auto">
      {/* Certificate Card */}
      <div 
        id="trust-certificate"
        ref={certificateRef}
        className={`w-full bg-surface border-2 ${borderColor} rounded-xl p-8 shadow-2xl relative overflow-hidden`}
      >
        {/* Decorative Background Pattern */}
        <div className="absolute inset-0 opacity-5 pointer-events-none" style={{
          backgroundImage: 'radial-gradient(circle at 2px 2px, white 1px, transparent 0)',
          backgroundSize: '24px 24px'
        }}></div>

        {/* Header */}
        <div className="flex flex-col md:flex-row items-center justify-between border-b border-outline pb-6 mb-6 relative z-10 gap-4">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-surface-container rounded-lg flex items-center justify-center border border-outline shadow-inner">
              <span className="material-symbols-outlined text-primary text-3xl">policy</span>
            </div>
            <div>
              <h2 className="text-2xl font-bold text-on-surface tracking-tight">DeepGuard+</h2>
              <p className="text-sm text-on-surface-variant font-medium tracking-widest uppercase">Trust Certificate</p>
            </div>
          </div>
          
          <div className={`flex items-center gap-2 px-4 py-2 rounded-full border border-current ${badgeColor}`}>
            <span className="material-symbols-outlined text-xl">{badgeIcon}</span>
            <span className="font-bold tracking-wide">{analysisResult?.verdict || 'UNKNOWN'}</span>
          </div>
        </div>

        {/* Body Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 relative z-10">
          {/* Left Column: Details */}
          <div className="space-y-5">
            <div>
              <p className="text-xs text-on-surface-variant uppercase tracking-wider mb-1">Analyzed File</p>
              <p className="text-lg text-on-surface font-medium truncate" title={fileName}>{fileName || 'Unknown File'}</p>
            </div>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-surface-container p-3 rounded-lg border border-outline">
                <p className="text-xs text-on-surface-variant mb-1 flex items-center gap-1">
                  <span className="material-symbols-outlined text-[16px]">analytics</span>
                  Confidence Score
                </p>
                <p className="text-xl text-on-surface font-bold">{analysisResult?.confidence || 0}%</p>
              </div>
              <div className="bg-surface-container p-3 rounded-lg border border-outline">
                <p className="text-xs text-on-surface-variant mb-1 flex items-center gap-1">
                  <span className="material-symbols-outlined text-[16px]">warning</span>
                  Risk Level
                </p>
                <p className="text-xl text-on-surface font-bold capitalize">{analysisResult?.riskLevel?.toLowerCase() || 'Unknown'}</p>
              </div>
            </div>

            <div>
              <p className="text-xs text-on-surface-variant uppercase tracking-wider mb-1">Scan Timestamp</p>
              <p className="text-sm text-on-surface font-mono">{new Date().toISOString()}</p>
            </div>
          </div>

          {/* Right Column: Visual Fingerprint */}
          <div className="flex flex-col items-center justify-center space-y-4 bg-surface-container/50 p-6 rounded-xl border border-outline">
            <p className="text-xs text-on-surface-variant uppercase tracking-wider w-full text-left">Media DNA Fingerprint</p>
            
            {/* 4x4 DNA Grid */}
            <div className="grid grid-cols-4 gap-1 w-32 h-32 p-2 bg-black rounded shadow-inner">
              {gridColors.map((color, idx) => (
                <div 
                  key={idx} 
                  className="w-full h-full rounded-sm"
                  style={{ backgroundColor: color }}
                />
              ))}
            </div>

            <div className="w-full">
              <p className="text-xs text-on-surface-variant mb-1 flex items-center gap-1">
                <span className="material-symbols-outlined text-[16px]">tag</span>
                SHA-256 Hash
              </p>
              <p className="text-xs text-secondary font-mono break-all bg-black/40 p-2 rounded border border-outline/50 selection:bg-primary/30">
                {hash || 'N/A'}
              </p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 pt-4 border-t border-outline flex flex-col md:flex-row items-center justify-between text-xs text-on-surface-variant relative z-10 gap-2">
          <p className="flex items-center gap-1">
            <span className="material-symbols-outlined text-[14px]">shield</span>
            Generated by DeepGuard+ Forensic Systems
          </p>
          <p className="flex items-center gap-1">
            <span className="material-symbols-outlined text-[14px]">gavel</span>
            Compliant with DPDP Act 2023 & IT Act 2000
          </p>
        </div>
      </div>

      {/* Action Buttons (Not included in capture) */}
      <div className="flex items-center justify-end w-full gap-4">
        <button 
          onClick={handleCopyReport}
          className="flex items-center gap-2 px-5 py-2.5 rounded-lg border border-outline text-on-surface hover:bg-surface-container transition-all active:scale-95"
        >
          <span className="material-symbols-outlined text-[20px]">content_copy</span>
          Copy Report
        </button>
        <button 
          onClick={handleDownload}
          className="flex items-center gap-2 px-6 py-2.5 rounded-lg bg-inverse-primary text-white font-medium hover:bg-inverse-primary/90 transition-all shadow-lg shadow-inverse-primary/20 active:scale-95"
        >
          <span className="material-symbols-outlined text-[20px]">download</span>
          Download as PNG
        </button>
      </div>
    </div>
  );
};

export default TrustCertificate;
